name: Build macOS

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build macos
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: "Install Homebrew"
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: "Install required packages."
        run: |
          brew update
          brew install ninja libomp

      - name: "Build"
        run: |
          rm -rf build && mkdir build && cd build
          cmake -DCMAKE_C_COMPILER=gcc-14 \
                -DCMAKE_CXX_COMPILER=g++-14 \
                -DCMAKE_BUILD_TYPE=Release \
                -GNinja .. 
          ninja
